### ISSUE TITLE
SprintBackLogの整理

### ISSUE THREAD

**Issue by Ayane2003** [furushuns/Balance#14]

**Comment by Ayane2003** [comment]
確認お願いします

**Comment by ShunFurusawa** [comment]
Programerのラベルは青の方が見やすそうなきがしました。あとは、現状ほとんどだれもこのProjectsを使ってないから企画が通ったら具体的な運用方法を決めて（誰がissue作る？誰がレビューする？クローズは？）、簡単な使い方を他メンバーに共有するといいと思う。そのときは手伝います。

**Comment by ShunFurusawa** [comment]
あ、あと一つのissueを複数にアサインすると一人一人の進捗が確認しずらいっぽいからそこも要検討かも。（今回の場合、デザイナー1人がコンセプトアート完成させたからDoneに移動させたら全員作り終わったみたいな感じになってしまった）

**Comment by ShunFurusawa** [comment]
ごめんあと一つ、これから多分issueすごい増えると思うから「全体」のLayoutだけでもBoardからTableに変えると仕分けがしやすいかもと思いました。

**Comment by Ayane2003** [comment]
この件に関して同じこと考えてた。
これからはタスクの細分化したり、複数作ることでissueのアサインは1人にする予定です。
