### ISSUE TITLE
チーム名とゲーム名決める

### ISSUE THREAD

**Issue by ShunFurusawa** [furushuns/Balance#6]
furushusはいやです

**Comment by ShunFurusawa** [comment]
あとはSprtintBackLog上の整理とかラベル付け等やってくれると泣いて喜びます。

**Comment by Ayane2003** [comment]
了解
来週までにしておきます
名前はもうちょい待って欲しい

**Comment by Ayane2003** [comment]
Thread＋Friendsより「スレンズ」

**Comment by Ayane2003** [comment]
チーム名はゲーム名と同じにします。
仮で傾くの英単語「tilt」から「ティルテット」にしました
